App features implementation
Yvad60/spotlight pull request #1
Opened 2023-04-16 20:50 UTC by Yvad60

Work in progress...

2023-05-04 11:03 UTC, Odile078 requested changes

2023-05-04 11:03 UTC, Odile078 commented on src/components/sections/MoreNews.jsx
> +              data.slice(4).map((article, index) => <NewsCard article={article} key={index} />)}
It will be better to use a ternary operator than checking whether **isFetching** is true and then if it's not again.

 Like this,
```suggestion
            {isFetching?
              Array(6)
                .fill(0)
                .map((_item, index) => <NewsCardSkeleton key={index} />)
             : data?.slice(4).map((article, index) => <NewsCard article={article} key={index} />)}
```

2023-05-04 11:03 UTC, Odile078 commented on src/components/sections/MoreNews.jsx
> +              data.slice(4).map((article, index) => <NewsCard article={article} key={index} />)}
It would be better to use optional chaining "?." than logical AND(&&), when checking a value before chaining it, as it's more clear and cleaner.

2023-05-04 11:03 UTC, Odile078 commented on src/components/ui/Publishers.jsx
> +                        <BsGlobe className="hidden sm:inline" />{" "}
It would be better to remove this empty space

2023-05-04 11:03 UTC, Odile078 commented on src/components/ui/Publishers.jsx
> +            visiblePublishers.map((publisher) => (
It will be better to use a ternary operator than checking whether isFetching is true and then if it's not again.
```suggestion
          {isFetching?
            Array(8)
              .fill(0)
              .map((_item, index) => <PublisherRowSkeleton key={index} />)
            : visiblePublishers?.map((publisher) => (
```

2023-05-04 11:03 UTC, Odile078 commented on src/components/ui/SearchInput.jsx
> +  const handleChange = (event) => {
Since the logic inside this function fits on one line, you can remove the curly braces.

2023-05-04 11:03 UTC, Odile078 commented on src/components/ui/SearchInput.jsx
> +  const handleSearch = () => {
same here, since the logic inside this function fits on one line, you can remove the curly braces.

2023-05-04 11:19 UTC, Yvad60 commented on src/components/sections/MoreNews.jsx
> +              data.slice(4).map((article, index) => <NewsCard article={article} key={index} />)}
That would be more clean👍

2023-05-09 13:22 UTC, Odile078 approved these changes

2023-05-10 15:08 UTC, merged

2023-08-17 14:58 UTC, Yvad60 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure they also do a full cloning exercise](https://trello.com/c/G4tn018q/7-make-sure-they-also-do-a-full-cloning-exercise)